import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "./AuthProvider";
import { ApolloWrapper } from "./ApolloWrapper";
import { CartContextWrapper } from "./CartContext";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PPBookShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "text-dark-brown")}>
        <AuthProvider>
          <ApolloWrapper>
            <CartContextWrapper>
              <Header />
              <main className="flex-1 min-h-[70vh]">{children}</main>
              <Footer />
              <Toaster />
            </CartContextWrapper>
          </ApolloWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
